<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The criteria used to filter the list of brands.
 *
 * Generated from protobuf message <code>server.public_api.BrandFilterCriteria</code>
 */
class BrandFilterCriteria extends \Google\Protobuf\Internal\Message
{
    /**
     * Which organization to list brands from.
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     */
    private $organization_id = '';

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * Which organization to list brands from.
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Which organization to list brands from.
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->organization_id = $var;

        return $this;
    }

}

