<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A document that is part of a property claim, auto claim or property inspection
 *
 * Generated from protobuf message <code>server.public_api.DocumentInfo</code>
 */
class DocumentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The filename for the document. May have been user provided or autogenerated.
     *
     * Generated from protobuf field <code>string filename = 1;</code>
     */
    private $filename = '';
    /**
     * The MIME content type for the document.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     */
    private $content_type = '';
    /**
     * A signed url that can be used to download the document.
     * Is valid for 24 hours.
     *
     * Generated from protobuf field <code>string download_uri = 3;</code>
     */
    private $download_uri = '';

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * The filename for the document. May have been user provided or autogenerated.
     *
     * Generated from protobuf field <code>string filename = 1;</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * The filename for the document. May have been user provided or autogenerated.
     *
     * Generated from protobuf field <code>string filename = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->filename = $var;

        return $this;
    }

    /**
     * The MIME content type for the document.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * The MIME content type for the document.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

    /**
     * A signed url that can be used to download the document.
     * Is valid for 24 hours.
     *
     * Generated from protobuf field <code>string download_uri = 3;</code>
     * @return string
     */
    public function getDownloadUri()
    {
        return $this->download_uri;
    }

    /**
     * A signed url that can be used to download the document.
     * Is valid for 24 hours.
     *
     * Generated from protobuf field <code>string download_uri = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_uri = $var;

        return $this;
    }

}

