<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>server.public_api.NewPropertyClaimInfo</code>
 */
class NewPropertyClaimInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The organization under which this claim lives
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     */
    private $organization_id = '';
    /**
     * The brand information used by this claim
     * Possible values can be obtained by calling
     * ListBrands
     *
     * Generated from protobuf field <code>uint64 brand_id = 2;</code>
     */
    private $brand_id = 0;
    /**
     * The insurer's identifier for a property claim
     * This is required when both assignment_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurer_identifier = 16;</code>
     */
    private $insurer_identifier = null;
    /**
     * The identifier used in the assignment software
     * This is required when both insurer_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue assignment_identifier = 17;</code>
     */
    private $assignment_identifier = null;
    /**
     * The indentifier used by the contractor for the property claim
     * This is required when both insurer_identifier
     * and assignment_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue contractor_identifier = 18;</code>
     */
    private $contractor_identifier = null;
    /**
     * The full name of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_name = 19;</code>
     */
    private $policyholder_name = null;
    /**
     * A free-form text field used to write details of the property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue loss_details = 20;</code>
     */
    private $loss_details = null;
    /**
     * The date of the loss
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_of_loss = 21;</code>
     */
    private $date_of_loss = null;
    /**
     * The date the property claim was first created
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_claim_created = 22;</code>
     */
    private $date_claim_created = null;
    /**
     * The full street address of the property claim,
     * including city/state/country/postal-code
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue full_address = 23;</code>
     */
    private $full_address = null;
    /**
     * The name of the insurance company insuring the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurance_company_name = 24;</code>
     */
    private $insurance_company_name = null;
    /**
     * The name of the adjuster working on this property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue adjuster_name = 25;</code>
     */
    private $adjuster_name = null;
    /**
     * The name of the broken or agent working with the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue broker_or_agent_name = 26;</code>
     */
    private $broker_or_agent_name = null;
    /**
     * The email address of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_email_address = 27;</code>
     */
    private $policyholder_email_address = null;
    /**
     * The phone_number of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_phone_number = 28;</code>
     */
    private $policyholder_phone_number = null;
    /**
     * The policy # for the insured property
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policy_number = 29;</code>
     */
    private $policy_number = null;
    /**
     * The annual depreciation to use when no depreciation category
     * is picked, as a unitless ratio. If left blank, there is no
     * default and ACV is not calculated for an item until a depreciation
     * category is added to it
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue default_depreciation = 30;</code>
     */
    private $default_depreciation = null;
    /**
     * The maximum total depreciation that can ever be applied to an item,
     * as a unitless ratio. This applies on top of default_depreciation.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue max_depreciation = 31;</code>
     */
    private $max_depreciation = null;
    /**
     * The sales tax to add to the computed total RCV, as a unitless ratio.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue sales_tax = 32;</code>
     */
    private $sales_tax = null;
    /**
     * The estimated amount that will be spent on the emergency portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value emergency_estimate = 33;</code>
     */
    private $emergency_estimate = null;
    /**
     * The estimated amount that will be spent on the repair portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value repair_estimate = 34;</code>
     */
    private $repair_estimate = null;
    /**
     * The estimated amount that will be spent on the contents portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value contents_estimate = 35;</code>
     */
    private $contents_estimate = null;

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * The organization under which this claim lives
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * The organization under which this claim lives
     *
     * Generated from protobuf field <code>string organization_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * The brand information used by this claim
     * Possible values can be obtained by calling
     * ListBrands
     *
     * Generated from protobuf field <code>uint64 brand_id = 2;</code>
     * @return int|string
     */
    public function getBrandId()
    {
        return $this->brand_id;
    }

    /**
     * The brand information used by this claim
     * Possible values can be obtained by calling
     * ListBrands
     *
     * Generated from protobuf field <code>uint64 brand_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBrandId($var)
    {
        GPBUtil::checkUint64($var);
        $this->brand_id = $var;

        return $this;
    }

    /**
     * The insurer's identifier for a property claim
     * This is required when both assignment_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurer_identifier = 16;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getInsurerIdentifier()
    {
        return $this->insurer_identifier;
    }

    /**
     * The insurer's identifier for a property claim
     * This is required when both assignment_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurer_identifier = 16;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setInsurerIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->insurer_identifier = $var;

        return $this;
    }

    /**
     * The identifier used in the assignment software
     * This is required when both insurer_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue assignment_identifier = 17;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getAssignmentIdentifier()
    {
        return $this->assignment_identifier;
    }

    /**
     * The identifier used in the assignment software
     * This is required when both insurer_identifier
     * and contractor_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue assignment_identifier = 17;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setAssignmentIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->assignment_identifier = $var;

        return $this;
    }

    /**
     * The indentifier used by the contractor for the property claim
     * This is required when both insurer_identifier
     * and assignment_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue contractor_identifier = 18;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getContractorIdentifier()
    {
        return $this->contractor_identifier;
    }

    /**
     * The indentifier used by the contractor for the property claim
     * This is required when both insurer_identifier
     * and assignment_identifier are blank
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue contractor_identifier = 18;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setContractorIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->contractor_identifier = $var;

        return $this;
    }

    /**
     * The full name of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_name = 19;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getPolicyholderName()
    {
        return $this->policyholder_name;
    }

    /**
     * The full name of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_name = 19;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPolicyholderName($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->policyholder_name = $var;

        return $this;
    }

    /**
     * A free-form text field used to write details of the property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue loss_details = 20;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getLossDetails()
    {
        return $this->loss_details;
    }

    /**
     * A free-form text field used to write details of the property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue loss_details = 20;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setLossDetails($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->loss_details = $var;

        return $this;
    }

    /**
     * The date of the loss
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_of_loss = 21;</code>
     * @return \Server\Public_api\SymbolicDate
     */
    public function getDateOfLoss()
    {
        return $this->date_of_loss;
    }

    /**
     * The date of the loss
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_of_loss = 21;</code>
     * @param \Server\Public_api\SymbolicDate $var
     * @return $this
     */
    public function setDateOfLoss($var)
    {
        GPBUtil::checkMessage($var, \Server\Public_api\SymbolicDate::class);
        $this->date_of_loss = $var;

        return $this;
    }

    /**
     * The date the property claim was first created
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_claim_created = 22;</code>
     * @return \Server\Public_api\SymbolicDate
     */
    public function getDateClaimCreated()
    {
        return $this->date_claim_created;
    }

    /**
     * The date the property claim was first created
     * Will default to today's date in the UTC+0 timezone.
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate date_claim_created = 22;</code>
     * @param \Server\Public_api\SymbolicDate $var
     * @return $this
     */
    public function setDateClaimCreated($var)
    {
        GPBUtil::checkMessage($var, \Server\Public_api\SymbolicDate::class);
        $this->date_claim_created = $var;

        return $this;
    }

    /**
     * The full street address of the property claim,
     * including city/state/country/postal-code
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue full_address = 23;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getFullAddress()
    {
        return $this->full_address;
    }

    /**
     * The full street address of the property claim,
     * including city/state/country/postal-code
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue full_address = 23;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setFullAddress($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->full_address = $var;

        return $this;
    }

    /**
     * The name of the insurance company insuring the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurance_company_name = 24;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getInsuranceCompanyName()
    {
        return $this->insurance_company_name;
    }

    /**
     * The name of the insurance company insuring the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue insurance_company_name = 24;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setInsuranceCompanyName($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->insurance_company_name = $var;

        return $this;
    }

    /**
     * The name of the adjuster working on this property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue adjuster_name = 25;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getAdjusterName()
    {
        return $this->adjuster_name;
    }

    /**
     * The name of the adjuster working on this property claim
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue adjuster_name = 25;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setAdjusterName($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->adjuster_name = $var;

        return $this;
    }

    /**
     * The name of the broken or agent working with the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue broker_or_agent_name = 26;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getBrokerOrAgentName()
    {
        return $this->broker_or_agent_name;
    }

    /**
     * The name of the broken or agent working with the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue broker_or_agent_name = 26;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setBrokerOrAgentName($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->broker_or_agent_name = $var;

        return $this;
    }

    /**
     * The email address of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_email_address = 27;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getPolicyholderEmailAddress()
    {
        return $this->policyholder_email_address;
    }

    /**
     * The email address of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_email_address = 27;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPolicyholderEmailAddress($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->policyholder_email_address = $var;

        return $this;
    }

    /**
     * The phone_number of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_phone_number = 28;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getPolicyholderPhoneNumber()
    {
        return $this->policyholder_phone_number;
    }

    /**
     * The phone_number of the policyholder
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policyholder_phone_number = 28;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPolicyholderPhoneNumber($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->policyholder_phone_number = $var;

        return $this;
    }

    /**
     * The policy # for the insured property
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policy_number = 29;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getPolicyNumber()
    {
        return $this->policy_number;
    }

    /**
     * The policy # for the insured property
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue policy_number = 29;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPolicyNumber($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->policy_number = $var;

        return $this;
    }

    /**
     * The annual depreciation to use when no depreciation category
     * is picked, as a unitless ratio. If left blank, there is no
     * default and ACV is not calculated for an item until a depreciation
     * category is added to it
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue default_depreciation = 30;</code>
     * @return \Google\Protobuf\DoubleValue
     */
    public function getDefaultDepreciation()
    {
        return $this->default_depreciation;
    }

    /**
     * The annual depreciation to use when no depreciation category
     * is picked, as a unitless ratio. If left blank, there is no
     * default and ACV is not calculated for an item until a depreciation
     * category is added to it
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue default_depreciation = 30;</code>
     * @param \Google\Protobuf\DoubleValue $var
     * @return $this
     */
    public function setDefaultDepreciation($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\DoubleValue::class);
        $this->default_depreciation = $var;

        return $this;
    }

    /**
     * The maximum total depreciation that can ever be applied to an item,
     * as a unitless ratio. This applies on top of default_depreciation.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue max_depreciation = 31;</code>
     * @return \Google\Protobuf\DoubleValue
     */
    public function getMaxDepreciation()
    {
        return $this->max_depreciation;
    }

    /**
     * The maximum total depreciation that can ever be applied to an item,
     * as a unitless ratio. This applies on top of default_depreciation.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue max_depreciation = 31;</code>
     * @param \Google\Protobuf\DoubleValue $var
     * @return $this
     */
    public function setMaxDepreciation($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\DoubleValue::class);
        $this->max_depreciation = $var;

        return $this;
    }

    /**
     * The sales tax to add to the computed total RCV, as a unitless ratio.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue sales_tax = 32;</code>
     * @return \Google\Protobuf\DoubleValue
     */
    public function getSalesTax()
    {
        return $this->sales_tax;
    }

    /**
     * The sales tax to add to the computed total RCV, as a unitless ratio.
     *
     * Generated from protobuf field <code>.google.protobuf.DoubleValue sales_tax = 32;</code>
     * @param \Google\Protobuf\DoubleValue $var
     * @return $this
     */
    public function setSalesTax($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\DoubleValue::class);
        $this->sales_tax = $var;

        return $this;
    }

    /**
     * The estimated amount that will be spent on the emergency portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value emergency_estimate = 33;</code>
     * @return \Google\Protobuf\UInt64Value
     */
    public function getEmergencyEstimate()
    {
        return $this->emergency_estimate;
    }

    /**
     * The estimated amount that will be spent on the emergency portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value emergency_estimate = 33;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setEmergencyEstimate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->emergency_estimate = $var;

        return $this;
    }

    /**
     * The estimated amount that will be spent on the repair portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value repair_estimate = 34;</code>
     * @return \Google\Protobuf\UInt64Value
     */
    public function getRepairEstimate()
    {
        return $this->repair_estimate;
    }

    /**
     * The estimated amount that will be spent on the repair portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value repair_estimate = 34;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setRepairEstimate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->repair_estimate = $var;

        return $this;
    }

    /**
     * The estimated amount that will be spent on the contents portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value contents_estimate = 35;</code>
     * @return \Google\Protobuf\UInt64Value
     */
    public function getContentsEstimate()
    {
        return $this->contents_estimate;
    }

    /**
     * The estimated amount that will be spent on the contents portion
     * of the property claim, expressed in hundredths of the local currency.
     *
     * Generated from protobuf field <code>.google.protobuf.UInt64Value contents_estimate = 35;</code>
     * @param \Google\Protobuf\UInt64Value $var
     * @return $this
     */
    public function setContentsEstimate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt64Value::class);
        $this->contents_estimate = $var;

        return $this;
    }

}

