<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The criteria used to filter the list of organizations.
 * Currently empty, always fetches the whole list.
 *
 * Generated from protobuf message <code>server.public_api.OrganizationFilterCriteria</code>
 */
class OrganizationFilterCriteria extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

}

