<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Information about an organization.
 * Currently limited to just its identifier,
 * for use in other searches.
 *
 * Generated from protobuf message <code>server.public_api.OrganizationInfo</code>
 */
class OrganizationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * A UUID identifying the organization
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * A UUID identifying the organization
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * A UUID identifying the organization
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

