<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The criteria used to filter the property claims pictures.
 *
 * Generated from protobuf message <code>server.public_api.PropertyClaimPictureFilterCriteria</code>
 */
class PropertyClaimPictureFilterCriteria extends \Google\Protobuf\Internal\Message
{
    /**
     * Which property claim to list pictures from
     *
     * Generated from protobuf field <code>uint64 claim_id = 1;</code>
     */
    private $claim_id = 0;

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * Which property claim to list pictures from
     *
     * Generated from protobuf field <code>uint64 claim_id = 1;</code>
     * @return int|string
     */
    public function getClaimId()
    {
        return $this->claim_id;
    }

    /**
     * Which property claim to list pictures from
     *
     * Generated from protobuf field <code>uint64 claim_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClaimId($var)
    {
        GPBUtil::checkUint64($var);
        $this->claim_id = $var;

        return $this;
    }

}

