<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

/**
 * Protobuf enum <code>Server\Public_api\SymbolicDate\Month</code>
 */
class SymbolicDate_Month
{
    /**
     * Generated from protobuf enum <code>January = 0;</code>
     */
    const January = 0;
    /**
     * Generated from protobuf enum <code>February = 1;</code>
     */
    const February = 1;
    /**
     * Generated from protobuf enum <code>March = 2;</code>
     */
    const March = 2;
    /**
     * Generated from protobuf enum <code>April = 3;</code>
     */
    const April = 3;
    /**
     * Generated from protobuf enum <code>May = 4;</code>
     */
    const May = 4;
    /**
     * Generated from protobuf enum <code>June = 5;</code>
     */
    const June = 5;
    /**
     * Generated from protobuf enum <code>July = 6;</code>
     */
    const July = 6;
    /**
     * Generated from protobuf enum <code>August = 7;</code>
     */
    const August = 7;
    /**
     * Generated from protobuf enum <code>September = 8;</code>
     */
    const September = 8;
    /**
     * Generated from protobuf enum <code>October = 9;</code>
     */
    const October = 9;
    /**
     * Generated from protobuf enum <code>November = 10;</code>
     */
    const November = 10;
    /**
     * Generated from protobuf enum <code>December = 11;</code>
     */
    const December = 11;
}

