<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encircle_public_api_v1.proto

namespace Server\Public_api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A date in symbolic format, divorced from timezone considerations,
 * and as such not corresponding to a specific instant in time.
 *
 * Generated from protobuf message <code>server.public_api.SymbolicDate</code>
 */
class SymbolicDate extends \Google\Protobuf\Internal\Message
{
    /**
     * Year in the proleptic Gregorian calendar
     *
     * Generated from protobuf field <code>uint64 year = 1;</code>
     */
    private $year = 0;
    /**
     * Month of the year
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate.Month month = 2;</code>
     */
    private $month = 0;
    /**
     * Day of the month, indexed starting from 1
     *
     * Generated from protobuf field <code>uint32 day = 3;</code>
     */
    private $day = 0;

    public function __construct() {
        \GPBMetadata\EncirclePublicApiV1::initOnce();
        parent::__construct();
    }

    /**
     * Year in the proleptic Gregorian calendar
     *
     * Generated from protobuf field <code>uint64 year = 1;</code>
     * @return int|string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Year in the proleptic Gregorian calendar
     *
     * Generated from protobuf field <code>uint64 year = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkUint64($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Month of the year
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate.Month month = 2;</code>
     * @return int
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * Month of the year
     *
     * Generated from protobuf field <code>.server.public_api.SymbolicDate.Month month = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMonth($var)
    {
        GPBUtil::checkEnum($var, \Server\Public_api\SymbolicDate_Month::class);
        $this->month = $var;

        return $this;
    }

    /**
     * Day of the month, indexed starting from 1
     *
     * Generated from protobuf field <code>uint32 day = 3;</code>
     * @return int
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Day of the month, indexed starting from 1
     *
     * Generated from protobuf field <code>uint32 day = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkUint32($var);
        $this->day = $var;

        return $this;
    }

}

